# Generated by Django 3.1.12 on 2021-08-02 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('customer_stripe_id', models.CharField(max_length=200, unique=True)),
                ('date_archived', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_product_json', jsonfield.fields.JSONField()),
                ('type_code', models.CharField(max_length=200, unique=True)),
                ('type_name_english', models.CharField(max_length=200, unique=True)),
                ('type_description_english', models.TextField()),
                ('product_id', models.CharField(max_length=200)),
                ('date_archived', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('trial_days', models.IntegerField()),
                ('expiry', models.DateField()),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('accepted_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_number', models.CharField(max_length=200, unique=True)),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('payment_amount', models.FloatField()),
                ('start_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('stripe_subscription_create_json', jsonfield.fields.JSONField()),
                ('stripe_subscription_cancel_json', jsonfield.fields.JSONField()),
                ('stripe_subscription_modify_json', jsonfield.fields.JSONField()),
                ('susbcription_id', models.CharField(max_length=200, unique=True)),
                ('subscription_status', models.CharField(max_length=200)),
                ('date_archived', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_subscription_monthly_payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_json', jsonfield.fields.JSONField()),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True)),
                ('date_archived', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersubscription')),
            ],
        ),
        migrations.CreateModel(
            name='user_monthly_invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=200, unique=True)),
                ('invoice_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeProductPrices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=200)),
                ('price_per_month', models.FloatField()),
                ('stripe_price_id', models.CharField(max_length=100, unique=True)),
                ('stripe_price_json', jsonfield.fields.JSONField()),
                ('date_archived', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('stripe_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stripeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomersCards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_stripe_id', models.CharField(max_length=200, unique=True)),
                ('payment_json', jsonfield.fields.JSONField()),
                ('card_name', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('exp_month', models.CharField(max_length=100)),
                ('exp_year', models.CharField(max_length=100)),
                ('last_4', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('stripe_customer_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stripecustomers')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUpdates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('stripe_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersubscription')),
            ],
        ),
    ]
