# Generated by Django 3.1.12 on 2021-08-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_productupdates_stripecustomers_stripecustomerscards_stripeproduct_stripeproductprices_user_monthly_i'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productupdates',
            table='user_product_updates',
        ),
        migrations.AlterModelTable(
            name='stripecustomers',
            table='user_stripe_customers',
        ),
        migrations.AlterModelTable(
            name='stripecustomerscards',
            table='user_stripe_customers_cards',
        ),
        migrations.AlterModelTable(
            name='stripeproduct',
            table='user_stripe_product',
        ),
        migrations.AlterModelTable(
            name='stripeproductprices',
            table='user_stripe_product_prices',
        ),
        migrations.AlterModelTable(
            name='user_monthly_invoice',
            table='user_monthly_invoice',
        ),
        migrations.AlterModelTable(
            name='user_subscription_monthly_payments',
            table='user_subscription_monthly_payments',
        ),
        migrations.AlterModelTable(
            name='userinvitation',
            table='user_invitation',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_user_profile',
        ),
        migrations.AlterModelTable(
            name='usersubscription',
            table='user_subscription',
        ),
    ]
