# Generated by Django 3.1.12 on 2021-08-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210817_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
